### ISSUE TITLE
Delete doc

### ISSUE THREAD

**Issue by islam2hamy** [Breta01/docus#36]
FATAL EXCEPTION: pool-1-thread-1
Process: com.bretahajek.docus, PID: 7450
java.lang.NoSuchMethodError: No virtual method toPath()Ljava/nio/file/Path; in class Ljava/io/File; or its super classes (declaration of 'java.io.File' appears in /system/framework/core-oj.jar)
	at d.a.a.a.b.b(:1)
	at c.b.a.f.run()
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:760)

Android : 7.1.2
Miui 11.0.2

**Comment by Breta01** [comment]
Hi @islam2hamy  thanks for pointing this out. It seems to be issue with one of the libraries I use:
https://github.com/Breta01/docus/blob/b733a1c76e545c4a000cf160af23adf8d1e72444/app/build.gradle#L84
Based on this issue it seems we should downgrade it to `2.5` (https://stackoverflow.com/questions/56970862/deletedirectory-java-lang-nosuchmethoderror-no-virtual-method-topath). 

If you want, you can create a pull request with the fix and I will approve it (You will then be listed as contributor 😉). Or else I will try to fix that soon.

**Comment by islam2hamy** [comment]
Hi @Breta01 ,
I will wait :)
